In [2]:
import numpy as np

In [3]:
A = np.array([1, 2, 3])

In [4]:
A = np.array([1, 2, 3]) # générateur par défaut, qui permet de convertir des listes (ou autres objets) en tableau ndarray
A = np.zeros((2, 3)) # tableau de 0 aux dimensions 2x3
B = np.ones((2, 3)) # tableau de 1 aux dimensions 2x3
C = np.random.randn(2, 3) # tableau aléatoire (distribution normale) aux dimensions 2x3
D = np.random.rand(2, 3) # tableau aléatoire (distribution uniforme)

E = np.random.randint(0, 10, [2, 3]) # tableau d'entiers aléatoires de 0 a 10 et de dimension 2x3

In [5]:
A = np.ones((2, 3), dtype=np.float16) # définit le type et la place a occuper sur la mémoire
B = np.eye(4, dtype=np.bool) # créer une matrice identité et convertit les éléments en type bool.

C:\Users\boris-thibaut.tondju\AppData\Local\Temp\ipykernel_17924\950731242.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.eye(4, dtype=np.bool) # créer une matrice identité et convertit les éléments en type bool.


In [6]:
A = np.linspace(1,10, 10)
B = np.arange(0, 10, 10)

#### 2. Attributs importants
#### size
#### shape

In [7]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
print(A.size) # le nombre d'éléments dans le tableau A
print(A.shape) # les dimensions du tableau A (sous forme de Tuple)
 
print(type(A.shape)) # voici la preuve que la shape est un tuple
 
print(A.shape[0]) # le nombre d'éléments dans la premiere dimension de A

6
(2, 3)
<class 'tuple'>
2


#### 3. Méthodes importantes
##### reshape() : pour redimensionner un tableau 
##### ravel() : pour applatir un tableau (qu'il ne fasse plus qu'une dimension)
##### squeeze() : quand une dimension est égale a 1, cette dimension disparait
##### concatenate() : assemble 2 tableaux ensemble selon un axes (existe aussi en hstack et vstack)

In [11]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
A = A.reshape((3, 2)) # redimensionne le tableau A (3 lignes, 2 colonnes)
A.ravel() # Aplatit le tableau A (une seule dimension)
A.squeeze() # élimine les dimensions "1" de A.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)
np.concatenate((A, B), axis=0) # axe 0 : équivalent de np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.concatenate((A, B), axis=1) # axe 1 : équivalent de np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

### Slicing et Indexing

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [16]:
# Pour acceder a la ligne 0, colonne 1
A[0, 1] 

2

In [17]:
# Pour selectionner les blocs de la ligne (0-1) colonne (0-1)
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [18]:
A[0:2, 0:2] = 10
print(A)

[[10 10  3]
 [10 10  6]]


## Boolean Indexing

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6]])
 
print(A<5) # masque booléen
 
print(A[A < 5]) # sous-ensemble filtré par le masque booléen
 
A[A<5] = 4 # convertit les valeurs sélectionnées.
print(A)

[[ True  True  True]
 [ True False False]]
[1 2 3 4]
[[4 4 4]
 [4 5 6]]


In [20]:
B = np.zeros((4, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
B[1:3 , 1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [22]:
C = np.zeros((5, 5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
C[::2, ::2] = 1
C

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])